[package]
name = "tokio-telnet"
edition = "2018"
version = "0.1.0"
authors = ["Hans W. Uhlig <huhlig@gmail.com>"]
description = "Telnet Library for Tokio"

[dependencies]
bytes = "0.5.1"
tokio = { version = "0.2" }
tokio-util = { version = "0.2", features = ["codec"] }
tracing = "0.1.10"